# Generated by Django 4.1 on 2023-05-03 09:36

import databaseManagementLocal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(help_text='pwd', max_length=30)),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('SecretKey', models.CharField(max_length=100)),
                ('Avatar', models.ImageField(height_field=300, upload_to=databaseManagementLocal.models.User.user_directory_path, width_field=300)),
                ('License', models.ImageField(upload_to=databaseManagementLocal.models.User.user_directory_path)),
                ('Type', models.IntegerField(choices=[(1, 'Customer'), (2, 'Seller'), (3, 'Deliverystaff'), (4, 'Admin')], default=1)),
                ('Member', models.IntegerField(choices=[(1, 'Cu'), (2, 'Ag'), (3, 'Au'), (4, 'Diamond')], default=1)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('MoneyDaily', models.IntegerField(default=0)),
                ('MoneyMonthly', models.IntegerField(default=0)),
                ('MoneySum', models.IntegerField(default=0)),
                ('Cart', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30)),
                ('Notes', models.CharField(blank=True, max_length=500)),
                ('Payment', models.IntegerField(choices=[(1, 'Alipay'), (2, 'Wechat'), (3, 'Balance')])),
                ('PayStatus', models.BooleanField(default=False)),
                ('ShopUID', models.IntegerField()),
                ('DeliveryStaffUID', models.IntegerField(blank=True)),
                ('DeliveryState', models.IntegerField(choices=[(0, 'Nojiedan'), (1, 'Nodeliverystaff'), (2, 'Noqucan'), (3, 'Qucaning'), (4, 'Onroad'), (5, 'Done')], default=0)),
                ('Cart', models.JSONField()),
                ('MoneySum', models.FloatField(max_length=10)),
                ('UserUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManagementLocal.user')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('FoodID', models.AutoField(primary_key=True, serialize=False)),
                ('FoodPhoto', models.ImageField(height_field=1080, upload_to=databaseManagementLocal.models.Menu.user_directory_path, width_field=1920)),
                ('Money', models.FloatField(max_length=10)),
                ('Discount', models.FloatField(max_length=10)),
                ('ShopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManagementLocal.user')),
            ],
        ),
    ]
