# Generated by Django 4.1 on 2023-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManagementLocal', '0003_alter_user_avatar_alter_user_cart_alter_user_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NewSessionToken',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
