# Generated by Django 4.1 on 2023-05-06 01:09

import databaseManagementLocal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManagementLocal', '0007_remove_user_newsessiontoken_alter_user_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='License',
            field=models.ImageField(blank=True, upload_to=databaseManagementLocal.models.User.user_directory_path),
        ),
    ]
